services: 
  backend:
    container_name: ft-backend
    build: backend/
    command: sh -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8080"
    expose:
      - 8080
    
    ports: 
      - 8080:8080
    
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
    volumes:
      - $PWD/backend:/app

    depends_on:
      - db
  
  db: 
    image: postgres:11-alpine 
    container_name: ft-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGPORT=5432
      - POSTGRES_USER=postgres

    expose:
      - 5432

    ports: 
      - 5432:5432
  
  frontend:
    container_name: ft-frontend
    build: frontend
    ports:
      - 3000:3000
    volumes:
      - $PWD/frontend:/app

volumes:
  postgres_data:
