# Generated by Django 4.1.2 on 2022-10-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_created_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answers',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
